<?php

namespace App\Models;

use App\Observers\ProductObserver;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory, CrudTrait;

    protected $guarded = [];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    // protected static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub

    //     self::observe(ProductObserver::class);
    // }
}
